[package]
name = "redixel"
description = "Public façade and entry point for the Redixel engine."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[features]
net = ["dep:redixel-net", "redixel-runtime/net"]

[dependencies]
# Internal crates
redixel-core = { workspace = true, features = ["wgpu"] }
redixel-math = { workspace = true, features = ["wgpu"] }
redixel-platform = { workspace = true }
redixel-renderer = { workspace = true }
redixel-runtime = { workspace = true }
redixel-net = { workspace = true, optional = true }

# External crates
winit = { workspace = true }

[target.'cfg(target_os = "android")'.dependencies]
winit = { workspace = true, features = ["android-native-activity"] }