[workspace]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[package]
name = "triangle"
version = "0.1.0"
edition = "2024"
publish = false

[package.metadata.game]
title = "Triangle"
description = "A fundamental rendering test displaying a 2D colored triangle using the Redixel rendering pipeline."
tags = ["2D", "Rendering"]

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
# Internal crates
redixel = { path = "../../crates/redixel" }

# External crates
log = "0.4"
