[package]
name = "redixel-math"
description = "High-performance linear algebra and math primitives for the Redixel engine."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[features]
wgpu = ["dep:wgpu"]

[dependencies]
wgpu = { workspace = true, optional = true }

[package.metadata.docs.rs]
all-features = true